services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - POSTGRES_USER=foobarbaz
      - POSTGRES_DB=foobarbaz
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:8.2-alpine
    ports:
        - 6379:6379
    command: 'redis-server --bind 0.0.0.0'

volumes:
  pg_data:
    name: pg_data
