import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="flex">
          <div className="w-60 h-screen"></div>
          <div className="flex-1 p-2 min-h-screen flex flex-col p-2">
            <div className="flex-1 p-6 border border-gray-200 rounded-lg">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
