import type { Metadata } from "next";
import "./globals.css";
import { AuthKitProvider, Impersonation } from "@workos-inc/authkit-nextjs/components";
import { Banknote, Inbox, LucideIcon, Receipt } from "lucide-react";
import { ClientProvider } from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navigation = ({
  title,
  items,
}: {
  title?: string;
  items: Array<{
    icon:
      | {
          type: "lucide";
          value: LucideIcon;
        }
      | {
          type: "group";
          value: string;
        }
      | {
          type: "user";
          value: string;
        };
    name: string;
    href: string;
  }>;
}) => {
  return (
    <div className="flex flex-col">
      {title && <h2 className="px-4 text-xs font-medium text-gray-400">{title}</h2>}
      <ul className="flex flex-col mt-2 mb-5">
        {items.map(({ icon, name, href }) => (
          <li className="flex py-0.5 cursor-default" key={name}>
            <a
              href={href}
              className="font-medium px-3 py-2 flex items-center gap-3.5 rounded-md hover:bg-gray-900 pl-4.5 w-full cursor-default"
            >
              {icon.type === "lucide" && <icon.value size={18} className="text-gray-500" />}
              {icon.type === "group" && (
                <div className="w-4.5 h-4.5 border border-white/20 bg-gray-600 rounded-md">{icon.value}</div>
              )}
              {icon.type === "user" && (
                <div className="w-4.5 h-4.5 border border-white/20 bg-green-500 rounded-full"></div>
              )}
              <span className="text-sm text-gray-300">{name}</span>
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-gray-950 text-gray-400`}>
        <AuthKitProvider>
          <Impersonation />
          <ClientProvider>
            <section className="flex">
              <aside className="px-4 w-72 h-screen min-w-0 pt-6 pb-2 flex flex-col gap-1">
                <header className="flex items-center justify-between pl-3 py-2 pr-2">
                  <a href={"/"} className="flex items-center gap-3 cursor-default">
                    <div className="w-8 h-8 bg-linear-to-b from-green-500 to-green-600 rounded-lg border border-white/10 flex items-center justify-center">
                      <Banknote size={20} className="text-green-200" />
                    </div>
                    <span className="font-serif text-2xl font-medium text-white">Splitlet</span>
                  </a>
                </header>
                <Navigation
                  items={[
                    { icon: { type: "lucide", value: Inbox }, name: "Dashboard", href: "/" },
                    { icon: { type: "lucide", value: Receipt }, name: "Recent Activity", href: "/recent-activity" },
                  ]}
                />
                <Navigation
                  title="Groups"
                  items={[
                    { icon: { type: "group", value: "" }, name: "Japan Trip 2023", href: "/groups/abc" },
                    { icon: { type: "group", value: "" }, name: "Sydney New Years", href: "/groups/def" },
                    { icon: { type: "group", value: "" }, name: "Melbourne New Years", href: "/groups/ghi" },
                  ]}
                />
                <Navigation
                  title="Friends"
                  items={[
                    { icon: { type: "user", value: "" }, name: "John Doe", href: "/friends/abcd" },
                    { icon: { type: "user", value: "" }, name: "Jane Appleseed", href: "/friends/defg" },
                    { icon: { type: "user", value: "" }, name: "Bob Brown", href: "/friends/hijk" },
                    { icon: { type: "user", value: "" }, name: "Clover Clark", href: "/friends/lmno" },
                  ]}
                />
              </aside>
              <main className="flex-1 p-2 min-h-screen flex flex-col p-2 min-w-0">
                <div className="flex-1 p-8 border border-gray-800 bg-gray-900 rounded-lg shadow-sm flex flex-col">
                  {children}
                </div>
              </main>
            </section>
          </ClientProvider>
        </AuthKitProvider>
      </body>
    </html>
  );
}
